import type { Metadata } from "next";
import {NextIntlClientProvider, useMessages} from 'next-intl';
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import "./globals.css";
import Navbar from "@/components/navbar";
import Table from "@/components/table";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "USER PORTAL",
  description: "Generated by create next app",
};

interface RootLayoutProps{
  children: React.ReactNode;
  params:{
    locale:string;
  };
}

export default function RootLayout({
  children,
  params:{ locale },
}: Readonly<RootLayoutProps>) {
  const messages = useMessages();
  return (
    <html lang={locale}>
      <body className={inter.className}>
      <NextIntlClientProvider locale={locale} messages={messages}>
        <Navbar/>
        <div className="background-container">{children}</div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
